const routes = {
    home: "/",
    rooms: "/rooms",
    login: "/login",
    register: "/register",
    profile: "/profile",
    search: "/search/:query",
    detail: "/details/:id",
    manager: "/manager",
    addroom: "/manager/addroom",
    editroom: "/manager/editroom",
    listroom: "/manager/listroom",
    liststatus: "/manager/liststatus",
    admin: "/admin",
    pay: "/pay",
    listcus: "/admin/listcus",
    listemployee: "/employee",
    addemployee: "/employee/add",
    editemployee: "/employee/edit/:id",
    bookingByNV: "/booking",
    viewRental: "/view-rental",
    editRental: "/edit-rental",
    revenuereport: "/revenue",
    densityreport: "/desity",
};

export default routes;
